# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27264f1abdeccb26131b80739d8483ef5a323aeeeeac108f607c8f7330f8457f05022f2f964fd01211298edf0ece26ad7f708c745da6fc40beb7c84fd9909e2a

test:
  secret_key_base: 9b7d92900fedc04cb391aed5d70ee036015245d8397f0b4e471fad933e18cfb274d597895746424b52dcae429c704dcf41d6f9464ef2ca71c5b4bb552bd357b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
